Repository gaea-godot/gaea, pull requests merged in 2023-12, with the labels that each got.

#84 Fix bug with trying to use null GaeaGrids
  addons/gaea/generators/2D/generator_2d.gd
  addons/gaea/generators/3D/generator_3d.gd
Labels: 🐛 bug

#85 Fix bug with ChunkLoaders not generating on ready or trying to generate when there's no generator
  addons/gaea/others/chunk_loader_2d.gd
  addons/gaea/others/chunk_loader_3d.gd
Labels: 🐛 bug

#83 Add layers
  addons/gaea/generators/2D/cellular_generator/cellular_generator.gd
  addons/gaea/generators/2D/chunk_aware_generator_2d.gd
  addons/gaea/generators/2D/grid_2d.gd
  addons/gaea/generators/3D/chunk_aware_generator_3d.gd
  addons/gaea/generators/3D/grid_3d.gd
  addons/gaea/grid.gd
  addons/gaea/modifiers/2D/carver.gd
  addons/gaea/modifiers/2D/fill.gd
  addons/gaea/modifiers/2D/generate_borders.gd
  addons/gaea/modifiers/2D/heightmap_painter.gd
  addons/gaea/modifiers/2D/noise_painter.gd
  addons/gaea/modifiers/2D/remove_disconnected.gd
  addons/gaea/modifiers/2D/smooth.gd
  addons/gaea/modifiers/2D/walls.gd
  addons/gaea/modifiers/3D/carver_3d.gd
  addons/gaea/modifiers/3D/heightmap_painter_3d.gd
  addons/gaea/modifiers/3D/noise_painter_3d.gd
  addons/gaea/modifiers/modifier.gd
  addons/gaea/renderers/2D/tilemap_gaea_renderer.gd
  addons/gaea/renderers/3D/gridmap_gaea_renderer.gd
  addons/gaea/tile_info/tile_info.gd
  addons/gaea/tile_info/tilemap_tile_info.gd
  scenes/demos/cellular/cellular_demo.tscn
  scenes/demos/heightmap/chunks_heightmap_demo.tscn
  scenes/demos/heightmap/heightmap_demo.tscn
  scenes/demos/heightmap/terraria-like_generation_settings.tres
  scenes/demos/heightmap_3d/heightmap_3d_demo.tscn
  scenes/demos/noise/chunk_noise_demo.tscn
  scenes/demos/noise/island-tileset - Kenney.png
  scenes/demos/noise/noise_demo.tscn
  scenes/demos/walker/walker_demo.tscn
  scenes/demos/wave_function_2d/wave_function_generator_2d_demo.tscn
Labels: ✨ enhancement, 🛠 breaking

#87 Change `get_property_list` to `validate_property` where possible
  addons/gaea/generators/2D/walker_generator/walker_generator_settings.gd
  addons/gaea/tile_info/tilemap_tile_info.gd
Labels: ✨ enhancement

#89 Add additional signals
  addons/gaea/generators/2D/cellular_generator/cellular_generator.gd
  addons/gaea/generators/2D/chunk_aware_generator_2d.gd
  addons/gaea/generators/2D/heightmap_generator/heightmap_generator_2d.gd
  addons/gaea/generators/2D/noise_generator/noise_generator.gd
  addons/gaea/generators/2D/walker_generator/walker_generator.gd
  addons/gaea/generators/2D/wave_function_generator/wave_function_generator_2d.gd
  addons/gaea/generators/3D/chunk_aware_generator_3d.gd
  addons/gaea/generators/3D/heightmap_generator_3d/heightmap_generator_3d.gd
  addons/gaea/generators/generator.gd
  addons/gaea/renderers/2D/gaea_renderer_2d.gd
  addons/gaea/renderers/2D/tilemap_gaea_renderer.gd
  addons/gaea/renderers/3D/gaea_renderer_3d.gd
  addons/gaea/renderers/3D/gridmap_gaea_renderer.gd
  addons/gaea/renderers/gaea_renderer.gd
Labels: ✨ enhancement

#90 Add script templates to project
  script_templates/ChunkAwareGenerator2D/default.gd
  script_templates/ChunkAwareGenerator3D/default.gd
  script_templates/GaeaGenerator2D/default.gd
  script_templates/GaeaGenerator3D/default.gd
  script_templates/GaeaRenderer2D/default.gd
  script_templates/GaeaRenderer3D/default.gd
Labels: ✨ enhancement

#88 Changed the way the noise generator accepts data
  addons/gaea/generators/2D/noise_generator/noise_generator.gd
  addons/gaea/generators/2D/noise_generator/noise_generator_data.gd
  addons/gaea/generators/2D/noise_generator/noise_generator_settings.gd
  project.godot
  scenes/demos/noise/chunk_noise_demo.tscn
  scenes/demos/noise/noise_demo.tres
  scenes/demos/noise/noise_demo.tscn
Labels: ✨ enhancement, 🛠 breaking

#92 Add a `seed` property to generators, can be random or fixed.
  addons/gaea/generators/2D/heightmap_generator/heightmap_generator_2d.gd
  addons/gaea/generators/2D/heightmap_generator/heightmap_generator_2d_settings.gd
  addons/gaea/generators/2D/noise_generator/noise_generator.gd
  addons/gaea/generators/2D/noise_generator/noise_generator_settings.gd
  addons/gaea/generators/3D/heightmap_generator_3d/heightmap_generator_3d.gd
  addons/gaea/generators/3D/heightmap_generator_3d/heightmap_generator_3d_settings.gd
  addons/gaea/generators/generator.gd
  addons/gaea/modifiers/2D/carver.gd
  addons/gaea/modifiers/2D/chunk_aware_modifier_2d.gd
  addons/gaea/modifiers/2D/heightmap_painter.gd
  addons/gaea/modifiers/2D/noise_painter.gd
  addons/gaea/modifiers/3D/carver_3d.gd
  addons/gaea/modifiers/3D/chunk_aware_modifier_3d.gd
  addons/gaea/modifiers/3D/heightmap_painter_3d.gd
  addons/gaea/modifiers/3D/noise_painter_3d.gd
Labels: ✨ enhancement

#93 Add threshold visualizer to modifiers which use it
  addons/gaea/editor/inspector_plugin.gd
  addons/gaea/editor/threshold_visualizer.gd
  addons/gaea/modifiers/2D/carver.gd
  addons/gaea/modifiers/2D/noise_painter.gd
  addons/gaea/modifiers/3D/carver_3d.gd
  addons/gaea/modifiers/3D/noise_painter_3d.gd
Labels: ✨ enhancement
