Repository gaea-godot/gaea, pull requests merged in 2023-08, with the labels that each got.

#14 Add Fill Modifier
  addons/gaea/modifiers/fill_modifier.gd
  addons/gaea/modifiers/fill_modifier.svg
  addons/gaea/modifiers/fill_modifier.svg.import
  addons/gaea/modifiers/generate_borders_modifier.gd
  docs/assets/fill-showcase.png
  docs/modifiers.md
  scenes/demos/walker/walker_demo.tscn
Labels: enhancement

#26 Add modifier logos to modifiers.md
  docs/assets/icons/carver.svg
  docs/assets/icons/fill.svg
  docs/assets/icons/generate_borders.svg
  docs/assets/icons/heightmap_painter.svg
  docs/assets/icons/noise_painter.svg
  docs/assets/icons/remove_disconnected.svg
  docs/assets/icons/smooth.svg
  docs/assets/icons/walls.svg
  docs/modifiers.md
Labels: 📖 documentation

#27 Update FIll modifier
  addons/gaea/modifiers/fill.gd
  scenes/demos/heightmap/heightmap_demo.tscn
  scenes/demos/walker/walker_demo.tscn
Labels: ✨ enhancement

#28 Add update button
  addons/gaea/editor/download_update_panel.gd
  addons/gaea/editor/download_update_panel.tscn
  addons/gaea/editor/logo.png
  addons/gaea/editor/logo.png.import
  addons/gaea/editor/update_button.gd
  addons/gaea/editor/update_button.tscn
  addons/gaea/plugin.gd
Labels: ✨ enhancement

#29 Chunk system
  addons/gaea/chunk_loader.gd
  addons/gaea/generators/chunk_aware_generator.gd
  addons/gaea/generators/generator.gd
  addons/gaea/generators/heightmap_generator/heightmap_generator_2d.gd
  addons/gaea/generators/noise_generator/noise_generator.gd
  addons/gaea/modifiers/carver.gd
  addons/gaea/modifiers/chunk_aware_modifier.gd
  addons/gaea/modifiers/heightmap_painter.gd
  addons/gaea/modifiers/noise_painter.gd
  scenes/demos/heightmap/chunks_heightmap_demo.tscn
  scenes/demos/heightmap/test_actor.gd
  scenes/demos/noise/chunk_noise_demo.tscn
  scenes/demos/noise/noise_demo.tscn
Labels: ✨ enhancement

#35 Add missing icons
  addons/gaea/chunk_loader.gd
  addons/gaea/chunk_loader.svg
  addons/gaea/chunk_loader.svg.import
  addons/gaea/generators/chunk_aware_generator.gd
  addons/gaea/generators/chunk_aware_generator.svg
  addons/gaea/generators/chunk_aware_generator.svg.import
  addons/gaea/generators/generator.gd
  addons/gaea/generators/generator.svg
  addons/gaea/generators/generator.svg.import
  addons/gaea/generators/noise_generator/noise_generator.gd
  addons/gaea/generators/noise_generator/noise_generator.svg
  addons/gaea/generators/noise_generator/noise_generator.svg.import
  addons/gaea/generators/tile_info.gd
  addons/gaea/generators/tile_info.svg
  addons/gaea/generators/tile_info.svg.import
Labels: ✨ enhancement

#38 Add `use_generator_noise` property to HeightmapPainter
  addons/gaea/modifiers/chunk_aware_modifier.gd
  addons/gaea/modifiers/heightmap_painter.gd
  scenes/demos/heightmap/chunks_heightmap_demo.tscn
  scenes/demos/heightmap/heightmap_demo.tscn
  scenes/demos/heightmap/terraria-like_generation_settings.tres
  scenes/demos/noise/chunk_noise_demo.tscn
  scenes/demos/noise/noise_demo.tscn
Labels: ✨ enhancement
