Repository gaea-godot/gaea, pull requests merged in 2024-08, with the labels that each got.

#148 Clarify filtering in modifiers and add "Only Empty Cells" option
  addons/gaea/modifiers/modifier.gd
  docs/modifiers.md
  docs/resources.md
  scenes/demos/heightmap/terraria-like_generation_settings.tres
Labels: 📖 documentation, ✨ enhancement

#144 Add Advanced Modifier
  addons/gaea/editor/inspector_plugin.gd
  addons/gaea/editor/threshold_visualizer.gd
  addons/gaea/generators/2D/cellular_generator/cellular_generator_settings.gd
  addons/gaea/generators/2D/walker_generator/walker_generator_settings.gd
  addons/gaea/generators/2D/wave_function_generator/wave_function_generator_2d.gd
  addons/gaea/modifiers/2D/advanced_modifier.gd
  addons/gaea/modifiers/2D/advanced_modifier.svg
  addons/gaea/modifiers/2D/advanced_modifier.svg.import
  addons/gaea/modifiers/2D/conditions/condition_2d.gd
  addons/gaea/modifiers/2D/conditions/offset_condition_2d.gd
  addons/gaea/modifiers/3D/advanced_modifier.gd
  addons/gaea/modifiers/3D/carver_3d.gd
  addons/gaea/modifiers/3D/conditions/condition_3d.gd
  addons/gaea/modifiers/3D/conditions/offset_condition_3d.gd
  addons/gaea/modifiers/conditions/chance_condition.gd
  addons/gaea/modifiers/conditions/condition.gd
  addons/gaea/modifiers/conditions/condition.svg
  addons/gaea/modifiers/conditions/condition.svg.import
  addons/gaea/modifiers/conditions/noise_condition.gd
  addons/gaea/modifiers/modifier.gd
  docs/_sidebar.md
  docs/assets/icons/advanced_modifier.svg
  docs/assets/tutorials/advanced_modifier/3D.png
  docs/assets/tutorials/advanced_modifier/advanced_modifier_example.png
  docs/assets/tutorials/advanced_modifier/dungeon.png
  docs/assets/tutorials/advanced_modifier/offset_condition_example.png
  docs/assets/tutorials/advanced_modifier/setup.png
  docs/modifiers.md
  docs/tutorials/advanced_modifier.md
  project.godot
  scenes/demos/heightmap/chunks_heightmap_demo.tscn
  scenes/demos/heightmap/heightmap_demo.tscn
  scenes/demos/heightmap/terraria-like_generation_settings.tres
  scenes/demos/heightmap/tiles_packed.png
  scenes/demos/heightmap/tiles_packed.png.import
  scenes/demos/heightmap/tileset.tres
  scenes/demos/heightmap/tree.tscn
  scenes/demos/noise/noise_demo.tres
  scenes/demos/walker/tilemap_packed.png
  scenes/demos/walker/tilemap_packed.png.import
  scenes/demos/walker/walker_demo.tscn
Labels: ✨ enhancement

#150 Fix gaps between terrains in TilemapRenderer
  addons/gaea/renderers/2D/tilemap_gaea_renderer.gd
Labels: 🐛 bug

#151 Fix addon-breaking unnecesary code in modifier.gd
  addons/gaea/modifiers/modifier.gd
Labels: 🐛 bug

#152 Add air layer option in HeightmapGenerators
  addons/gaea/generators/2D/heightmap_generator/heightmap_generator_2d.gd
  addons/gaea/generators/2D/heightmap_generator/heightmap_generator_2d_settings.gd
  addons/gaea/generators/3D/heightmap_generator_3d/heightmap_generator_3d.gd
  addons/gaea/generators/3D/heightmap_generator_3d/heightmap_generator_3d_settings.gd
  scenes/demos/heightmap/terraria-like_generation_settings.tres
Labels: ✨ enhancement

#153 Make terrain gap fix toggleable
  addons/gaea/renderers/2D/tilemap_gaea_renderer.gd
Labels: ✨ enhancement

#160 Clarify chunk generation tutorial and make world_size hide when infinite
  addons/gaea/generators/2D/heightmap_generator/heightmap_generator_2d_settings.gd
  addons/gaea/generators/2D/noise_generator/noise_generator_settings.gd
  addons/gaea/generators/3D/heightmap_generator_3d/heightmap_generator_3d_settings.gd
  docs/assets/tutorials/chunk_generation/infinite.png
  docs/tutorials/chunk_generation.md
Labels: 📖 documentation, ✨ enhancement

#158 Update to 4.3 (Support TilemapLayers)
  addons/gaea/generators/2D/heightmap_generator/heightmap_generator_2d.gd
  addons/gaea/generators/2D/wave_function_generator/wave_function_generator_2d.gd
  addons/gaea/plugin.cfg
  addons/gaea/renderers/2D/tilemap_gaea_renderer.gd
  project.godot
  scenes/demos/cellular/cellular_demo.tscn
  scenes/demos/heightmap/chunks_heightmap_demo.tscn
  scenes/demos/heightmap/heightmap_demo.tscn
  scenes/demos/heightmap/terraria-like_generation_settings.tres
  scenes/demos/heightmap/tileset.tres
  scenes/demos/noise/noise_demo.tres
  scenes/demos/noise/noise_demo.tscn
  scenes/demos/wave_function_2d/wave_function_generator_2d_demo.tscn
Labels: ✨ enhancement, 🛠 breaking

#161 Change documentation to reflect 4.3 changes
  docs/assets/tutorials/chunk_generation/chunk-generation-loader.png
  docs/assets/tutorials/chunk_generation/chunk-generation-nodes.png
  docs/assets/tutorials/getting_started/scene-tree.png
  docs/assets/tutorials/getting_started/tilemap-layers.gif
  docs/resources.md
  docs/tutorials/chunk_generation.md
  docs/tutorials/getting_started.md
  scenes/demos/noise/chunk_noise_demo.tscn
  scenes/tutorials/getting_started/getting_started.tscn
Labels: 📖 documentation

#162 Add HeightmapGenerator tutorial
  docs/_sidebar.md
  docs/assets/tutorials/heightmap_generator/carver.png
  docs/assets/tutorials/heightmap_generator/cave_no_dirt_deleted.png
  docs/assets/tutorials/heightmap_generator/caves.png
  docs/assets/tutorials/heightmap_generator/filtering.png
  docs/assets/tutorials/heightmap_generator/heightmap_painter.png
  docs/assets/tutorials/heightmap_generator/id.png
  docs/assets/tutorials/heightmap_generator/initial_generation.png
  docs/assets/tutorials/heightmap_generator/nodes.png
  docs/assets/tutorials/heightmap_generator/settings.png
  docs/assets/tutorials/heightmap_generator/stone.png
  docs/generators/heightmap.md
  docs/tutorials/heightmap_generator.md
Labels: 📖 documentation

#163 Produce error if GaeaRenderer doesn't have a generator assigned
  addons/gaea/renderers/2D/tilemap_gaea_renderer.gd
  addons/gaea/renderers/3D/gridmap_gaea_renderer.gd
Labels: ✨ enhancement

#167 Fix generate_on_ready not working
  addons/gaea/renderers/2D/tilemap_gaea_renderer.gd
  addons/gaea/renderers/3D/gridmap_gaea_renderer.gd
Labels: 🐛 bug
