Repository gaea-godot/gaea, pull requests merged in 2024-06, with the labels that each got.

#121 Fixed an error in chunk aware modifiers where the filter property wasn't being validated
  addons/gaea/modifiers/2D/chunk_aware_modifier_2d.gd
  addons/gaea/modifiers/3D/chunk_aware_modifier_3d.gd
Labels: 🐛 bug

#120 Remove warning and allow using ChunkLoaders on a finite world
  addons/gaea/others/chunk_loader_2d.gd
  addons/gaea/others/chunk_loader_3d.gd
Labels: ✨ enhancement

#119 Check if a grid has a layer before looking it up
  addons/gaea/grid.gd
Labels: 🐛 bug

#116 Add threaded chunk loaders and renderers
  addons/gaea/generators/2D/chunk_aware_generator_2d.gd
  addons/gaea/generators/2D/heightmap_generator/heightmap_generator_2d.gd
  addons/gaea/generators/3D/chunk_aware_generator_3d.gd
  addons/gaea/generators/3D/heightmap_generator_3d/heightmap_generator_3d.gd
  addons/gaea/others/chunk_loader_3d.gd
  addons/gaea/others/threaded_chunk_loader_2d.gd
  addons/gaea/others/threaded_chunk_loader_3d.gd
  addons/gaea/renderers/2D/threaded_tilemap_gaea_renderer.gd
  addons/gaea/renderers/2D/tilemap_gaea_renderer.gd
  addons/gaea/renderers/3D/gridmap_gaea_renderer.gd
  addons/gaea/renderers/3D/threaded_gridmap_gaea_renderer.gd
  scenes/demos/heightmap/chunks_heightmap_demo.tscn
  scenes/demos/heightmap_3d/actor.gd
  scenes/demos/heightmap_3d/heightmap_3d_demo.tscn
  script_templates/Node/multithread_wrapper.gd
  script_templates/Node/thread_wrapper.gd
  script_templates/Node/thread_wrapper_queue.gd
Labels: ✨ enhancement

#122 Add a `load_closest_chunks_first` toggle to ChunkLoaders
  addons/gaea/others/chunk_loader_2d.gd
  addons/gaea/others/chunk_loader_3d.gd
  addons/gaea/others/threaded_chunk_loader_2d.gd
  addons/gaea/others/threaded_chunk_loader_3d.gd
  addons/gaea/renderers/2D/threaded_tilemap_gaea_renderer.gd
  addons/gaea/renderers/3D/threaded_gridmap_gaea_renderer.gd
  script_templates/Node/multithread_wrapper.gd
Labels: ✨ enhancement

#123 Fixed issue with mismatching tile sizes and added utility functions
  addons/gaea/generators/2D/chunk_aware_generator_2d.gd
  addons/gaea/generators/2D/generator_2d.gd
  addons/gaea/generators/3D/chunk_aware_generator_3d.gd
  addons/gaea/generators/3D/generator_3d.gd
  addons/gaea/others/chunk_loader_2d.gd
  addons/gaea/others/chunk_loader_3d.gd
  addons/gaea/renderers/2D/tilemap_gaea_renderer.gd
  addons/gaea/renderers/3D/gridmap_gaea_renderer.gd
Labels: 🐛 bug

#129 Make NoisePainter and Carver modifiers use min and max thresholds
  addons/gaea/editor/inspector_plugin.gd
  addons/gaea/editor/threshold_visualizer.gd
  addons/gaea/generators/2D/noise_generator/noise_generator_settings.gd
  addons/gaea/modifiers/2D/carver.gd
  addons/gaea/modifiers/2D/noise_painter.gd
  addons/gaea/modifiers/3D/carver_3d.gd
  addons/gaea/modifiers/3D/noise_painter_3d.gd
  scenes/demos/heightmap/terraria-like_generation_settings.tres
  scenes/demos/heightmap_3d/heightmap_3d_demo.tscn
Labels: ✨ enhancement, 🛠 breaking

#132 Fix `modifier.enabled` not working in chunks
  addons/gaea/generators/2D/chunk_aware_generator_2d.gd
  addons/gaea/generators/3D/chunk_aware_generator_3d.gd
Labels: 🐛 bug
