Repository gaea-godot/gaea, pull requests merged in 2025-04, with the labels that each got.

#227 Remove docs in favor of the new repository
  README.md
  docs/.gdignore
  docs/.nojekyll
  docs/README.md
  docs/_coverpage.md
  docs/_navbar.md
  docs/_sidebar.md
  docs/assets/devworm-thumbnail.jpg
  docs/assets/graph_system.png
  docs/assets/mrelipteach-thumbnail.jpg
  docs/assets/nuclear-throne-style-showcase.png
  docs/assets/terrain-showcase.png
  docs/assets/tutorials/anatomy-of-a-graph/bool_example.png
  docs/assets/tutorials/anatomy-of-a-graph/data_example.png
  docs/assets/tutorials/anatomy-of-a-graph/float_example.png
  docs/assets/tutorials/anatomy-of-a-graph/frame.png
  docs/assets/tutorials/anatomy-of-a-graph/map_example.png
  docs/assets/tutorials/anatomy-of-a-graph/material_example.png
  docs/assets/tutorials/anatomy-of-a-graph/range_example.png
  docs/assets/tutorials/anatomy-of-a-graph/slots.png
  docs/assets/tutorials/generating-terrain/complete-generation.png
  docs/assets/tutorials/generating-terrain/connected-nodes.png
  docs/assets/tutorials/generating-terrain/final-final.png
  docs/assets/tutorials/generating-terrain/final.png
  docs/assets/tutorials/generating-terrain/generation.png
  docs/assets/tutorials/generating-terrain/simplex-smooth-2d.png
  docs/assets/tutorials/generating-terrain/tilemap_material.png
  docs/contribute.md
  docs/how-gaea-works.md
  docs/index.html
  docs/logo.svg
  docs/modifiers.md
  docs/tutorials/README.md
  docs/tutorials/anatomy-of-a-graph.md
  docs/tutorials/generating-terrain.md
Labels: 📖 documentation

#219 Make RandomMaterial use weights for better modularity
  addons/gaea/resources/materials/random_material.gd
Labels: ✨ enhancement

#220 Improve display for Output Node with name and state
  addons/gaea/graph/components/slot.gd
  addons/gaea/graph/components/slot.tscn
  addons/gaea/graph/nodes/output_node.gd
  addons/gaea/resources/gaea_data.gd
  addons/gaea/resources/gaea_layer.gd
  scenes/walker_demo/floor_walker.tres
  scenes/walker_demo/scene.tscn
Labels: ✨ enhancement

#231 Allow making the Gaea editor floating
  addons/gaea/editor/node_popup.gd
  addons/gaea/editor/panel.gd
  addons/gaea/editor/panel.tscn
  addons/gaea/gaea.gd
Labels: ✨ enhancement

#239 Fix ThresholdMapper
  addons/gaea/graph/nodes/root/map/mappers/threshold_mapper.gd
Labels: 🐛 bug

#235 Improve `weights` Array Handling in `RandomMaterial`
  addons/gaea/resources/materials/random_material.gd
  scenes/walker_demo/floor_walker.tres
Labels: 🐛 bug

#238 Add ability to detach nodes from parent frame and to disable auto shrink in frames
  addons/gaea/editor/graph_edit.gd
  addons/gaea/editor/node_popup.gd
  addons/gaea/editor/panel.gd
Labels: 🔨 quality-of-life

#237 Add RandomFilter nodes
  addons/gaea/graph/nodes/root/data/filters/filter.gd
  addons/gaea/graph/nodes/root/data/filters/random_filter.gd
  addons/gaea/graph/nodes/root/data/filters/random_filter.gd.uid
  addons/gaea/graph/nodes/root/data/filters/random_filter.tres
  addons/gaea/graph/nodes/root/map/filters/random_filter.tres
  scenes/walker_demo/floor_walker.tres
  scenes/walker_demo/scene.tscn
  scenes/walker_demo/tileset.png
Labels: ✨ enhancement

#244 Fix MultiplyVector2
  addons/gaea/graph/nodes/root/vector/operations/multiply_vector2.tres
Labels: 🐛 bug

#250 Remove position output slot from FloorWalkerXY
  addons/gaea/graph/nodes/root/data/generation/floor_walker_xy.tres
Labels: 🐛 bug, ignore-for-release

#249 Add context menu for link interactions
  .gitignore
  addons/gaea/editor/link_popup.gd
  addons/gaea/editor/link_popup.gd.uid
  addons/gaea/editor/panel.gd
  addons/gaea/editor/panel.tscn
Labels: 🔨 quality-of-life

#246 Automatically add previews & allow multiple previews
  addons/gaea/graph/components/slot.gd
  addons/gaea/graph/nodes/node.gd
  addons/gaea/graph/nodes/node_slot.gd
  addons/gaea/graph/nodes/preview_texture.gd
  addons/gaea/graph/nodes/root/data/basic/fill.tres
  addons/gaea/graph/nodes/root/data/border/border.tres
  addons/gaea/graph/nodes/root/data/filters/distance_filter.tres
  addons/gaea/graph/nodes/root/data/filters/flags_filter.tres
  addons/gaea/graph/nodes/root/data/filters/random_filter.tres
  addons/gaea/graph/nodes/root/data/filters/threshold_filter.tres
  addons/gaea/graph/nodes/root/data/functions/data_complement.tres
  addons/gaea/graph/nodes/root/data/functions/data_difference.tres
  addons/gaea/graph/nodes/root/data/functions/data_intersection.tres
  addons/gaea/graph/nodes/root/data/functions/data_union.tres
  addons/gaea/graph/nodes/root/data/generation/floor_walker_xy.tres
  addons/gaea/graph/nodes/root/data/generation/floor_walker_xz.tres
  addons/gaea/graph/nodes/root/data/generation/snake_path_2d.tres
  addons/gaea/graph/nodes/root/data/noise/simplex_smooth_2D.tres
  addons/gaea/graph/nodes/root/data/noise/simplex_smooth_3D.tres
  addons/gaea/graph/nodes/root/data/operations/add.tres
  addons/gaea/graph/nodes/root/data/operations/add_datas.tres
  addons/gaea/graph/nodes/root/data/operations/divide.tres
  addons/gaea/graph/nodes/root/data/operations/divide_datas.tres
  addons/gaea/graph/nodes/root/data/operations/multiply.tres
  addons/gaea/graph/nodes/root/data/operations/multiply_datas.tres
  addons/gaea/graph/nodes/root/data/operations/substract.tres
  addons/gaea/graph/nodes/root/data/operations/substract_datas.tres
  addons/gaea/graph/nodes/root/input/world_size.tres
  addons/gaea/graph/nodes/root/map/filters/random_filter.tres
  addons/gaea/graph/nodes/root/map/functions/map_difference.tres
  addons/gaea/graph/nodes/root/map/functions/map_intersection.tres
  addons/gaea/graph/nodes/root/map/functions/map_union.tres
  addons/gaea/graph/nodes/root/map/mappers/basic_mapper.tres
  addons/gaea/graph/nodes/root/map/mappers/flags_mapper.tres
  addons/gaea/graph/nodes/root/map/mappers/threshold_mapper.tres
  addons/gaea/graph/nodes/root/map/mappers/value_mapper.tres
  addons/gaea/graph/nodes/root/map/placing/rules_placer.tres
  addons/gaea/graph/nodes/root/map/random/random_scatter.tres
  addons/gaea/graph/nodes/root/other/composition/compose_range.tres
  addons/gaea/graph/nodes/root/scalar/operations/add.tres
  addons/gaea/graph/nodes/root/scalar/operations/divide.tres
  addons/gaea/graph/nodes/root/scalar/operations/multiply.tres
  addons/gaea/graph/nodes/root/scalar/operations/substract.tres
  addons/gaea/graph/nodes/root/vector/composition/compose_vector2.tres
  addons/gaea/graph/nodes/root/vector/composition/compose_vector3.tres
  addons/gaea/graph/nodes/root/vector/decomposition/decompose_vector2.tres
  addons/gaea/graph/nodes/root/vector/decomposition/decompose_vector3.tres
  addons/gaea/graph/nodes/root/vector/operations/add_vector2.tres
  addons/gaea/graph/nodes/root/vector/operations/add_vector3.tres
  addons/gaea/graph/nodes/root/vector/operations/divide_vector2.tres
  addons/gaea/graph/nodes/root/vector/operations/divide_vector3.tres
  addons/gaea/graph/nodes/root/vector/operations/multiply_vector2.tres
  addons/gaea/graph/nodes/root/vector/operations/multiply_vector3.tres
  addons/gaea/graph/nodes/root/vector/operations/substract_vector2.tres
  addons/gaea/graph/nodes/root/vector/operations/substract_vector3.tres
  scenes/walker_demo/floor_walker.tres
  scenes/walker_demo/scene.tscn
Labels: ✨ enhancement

#248 Color titlebars & add missing icons
  addons/gaea/assets/slots/circle.svg
  addons/gaea/assets/slots/diamond.svg
  addons/gaea/assets/slots/hexagon.svg
  addons/gaea/assets/slots/hourglass.svg
  addons/gaea/assets/slots/hourglass.svg.import
  addons/gaea/assets/slots/ring.svg
  addons/gaea/assets/slots/ring.svg.import
  addons/gaea/assets/slots/rounded_square.svg
  addons/gaea/assets/slots/rounded_square.svg.import
  addons/gaea/assets/slots/square.svg
  addons/gaea/assets/slots/tag.svg
  addons/gaea/assets/slots/tag.svg.import
  addons/gaea/assets/slots/triangle.svg
  addons/gaea/graph/components/inputs/graph_node_parameter.gd
  addons/gaea/graph/components/slot.gd
  addons/gaea/graph/nodes/constant.gd
  addons/gaea/graph/nodes/node.gd
  addons/gaea/graph/nodes/node_resource.gd
  addons/gaea/graph/nodes/output_node.gd
  addons/gaea/graph/nodes/output_node_resource.gd
  addons/gaea/graph/nodes/variable_node_resource.gd
Labels: 🔨 quality-of-life

#255 Add missing args
  addons/gaea/graph/nodes/root/scalar/operations/add.tres
Labels: 🐛 bug, ignore-for-release

#254 Add missing UID
  addons/gaea/graph/nodes/root/data/filters/random_filter.tres
  addons/gaea/graph/nodes/root/map/filters/random_filter.tres
  scenes/walker_demo/floor_walker.tres
Labels: 🐛 bug

#257 Fix generator data assignment to prevent null reference errors
  addons/gaea/editor/panel.gd
  addons/gaea/nodes/generator.gd
Labels: 🐛 bug

#259 Implement reroute node functionality
  addons/gaea/editor/graph_edit.gd
  addons/gaea/editor/link_popup.gd
  addons/gaea/editor/panel.gd
  addons/gaea/editor/panel.tscn
  addons/gaea/graph/nodes/node.gd
  addons/gaea/graph/nodes/node_resource.gd
  addons/gaea/graph/nodes/reroute_node.gd
  addons/gaea/graph/nodes/reroute_node.gd.uid
  addons/gaea/graph/nodes/reroute_node.tscn
  addons/gaea/graph/nodes/reroute_node_resource.gd
  addons/gaea/graph/nodes/reroute_node_resource.gd.uid
  scenes/walker_demo/floor_walker.tres
  scenes/walker_demo/scene.tscn
Labels: ✨ enhancement

#270 Fix Create Node popup not resizing by making it a Window
  addons/gaea/editor/panel.gd
  addons/gaea/editor/panel.tscn
  addons/gaea/graph/nodes/root/data/border/border.tres
Labels: 🐛 bug

#240 Add Falloff node
  addons/gaea/graph/nodes/root/data/generation/falloff.tres
  addons/gaea/graph/nodes/root/data/generation/falloff_map.gd
  addons/gaea/graph/nodes/root/data/generation/falloff_map.gd.uid
Labels: ✨ enhancement

#274 Fix popup display and floating editor in single-window mode
  addons/gaea/editor/link_popup.gd
  addons/gaea/editor/node_popup.gd
  addons/gaea/editor/panel.gd
  addons/gaea/editor/panel.tscn
Labels: 🐛 bug, ignore-for-release

#275 Rename nodes and ensure unique access in panel
  addons/gaea/editor/panel.gd
  addons/gaea/editor/panel.tscn
Labels: 🐛 bug, ignore-for-release

#276 Prevent code execution during scene editing and free old bottom panel resources
  addons/gaea/editor/create_node_tree.gd
  addons/gaea/editor/link_popup.gd
  addons/gaea/editor/node_popup.gd
  addons/gaea/editor/panel.gd
  addons/gaea/gaea.gd
Labels: 🐛 bug

#278 Add missing uid and fix function type
  addons/gaea/graph/nodes/root/data/filters/random_filter.tres
  addons/gaea/graph/nodes/root/data/generation/falloff.tres
  addons/gaea/graph/nodes/root/data/generation/falloff_map.gd
  addons/gaea/graph/nodes/root/map/filters/random_filter.tres
  scenes/walker_demo/floor_walker.tres
Labels: 🐛 bug, ignore-for-release

#279 Renamed some variables to avoid warnings
  addons/gaea/graph/nodes/root/data/filters/filter.gd
  addons/gaea/graph/nodes/root/data/filters/random_filter.gd
  addons/gaea/graph/nodes/root/data/filters/threshold_filter.gd
  addons/gaea/graph/nodes/root/map/mappers/basic_mapper.gd
  addons/gaea/graph/nodes/root/map/mappers/threshold_mapper.gd
  addons/gaea/graph/nodes/root/map/random/random_scatter.gd
  addons/gaea/graph/nodes/root/vector/composition/compose_vector.gd
  addons/gaea/graph/nodes/root/vector/decomposition/decompose_vector.gd
Labels: 🐛 bug, ignore-for-release

#280 Fix mouse position overlay Z index
  addons/gaea/editor/panel.tscn
Labels: 🐛 bug, ignore-for-release

#281 Fix graph image url
  README.md
Labels: 🐛 bug, ignore-for-release

#283 Re-organize `panel.gd`
  addons/gaea/editor/create_node_popup.gd
  addons/gaea/editor/create_node_popup.gd.uid
  addons/gaea/editor/graph_edit.gd
  addons/gaea/editor/panel.gd
  addons/gaea/editor/panel.tscn
  addons/gaea/graph/nodes/node.gd
  addons/gaea/graph/nodes/node_resource.gd
  addons/gaea/graph/nodes/output_node_resource.gd
  addons/gaea/graph/nodes/reroute_node_resource.gd
  addons/gaea/graph/nodes/root/map/random/random_scatter.gd
  addons/gaea/graph/nodes/variable_node_resource.gd
Labels: 🧹 organization/clean-up

#285 Add missing tool declaration that prevent popup to close
  addons/gaea/editor/create_node_popup.gd
Labels: 🐛 bug, ignore-for-release

#288 Add debug group to `GaeaData`
  addons/gaea/resources/gaea_data.gd
Labels: 🧹 organization/clean-up

#291 Update resource configurations for PR #289
  addons/gaea/graph/nodes/root/data/basic/fill.tres
  addons/gaea/graph/nodes/root/data/border/border.tres
  addons/gaea/graph/nodes/root/data/filters/distance_filter.tres
  addons/gaea/graph/nodes/root/data/filters/flags_filter.tres
  addons/gaea/graph/nodes/root/data/filters/random_filter.tres
  addons/gaea/graph/nodes/root/data/filters/threshold_filter.tres
  addons/gaea/graph/nodes/root/data/functions/data_complement.tres
  addons/gaea/graph/nodes/root/data/functions/data_difference.tres
  addons/gaea/graph/nodes/root/data/functions/data_intersection.tres
  addons/gaea/graph/nodes/root/data/functions/data_union.tres
  addons/gaea/graph/nodes/root/data/generation/falloff.tres
  addons/gaea/graph/nodes/root/data/generation/floor_walker_xy.tres
  addons/gaea/graph/nodes/root/data/generation/floor_walker_xz.tres
  addons/gaea/graph/nodes/root/data/generation/snake_path_2d.tres
  addons/gaea/graph/nodes/root/data/noise/simplex_smooth_2D.tres
  addons/gaea/graph/nodes/root/data/noise/simplex_smooth_3D.tres
  addons/gaea/graph/nodes/root/data/operations/add.tres
  addons/gaea/graph/nodes/root/data/operations/add_datas.tres
  addons/gaea/graph/nodes/root/data/operations/data_operation.gd
  addons/gaea/graph/nodes/root/data/operations/datas_operation.gd
  addons/gaea/graph/nodes/root/data/operations/divide.tres
  addons/gaea/graph/nodes/root/data/operations/divide_datas.tres
  addons/gaea/graph/nodes/root/data/operations/multiply.tres
  addons/gaea/graph/nodes/root/data/operations/multiply_datas.tres
  addons/gaea/graph/nodes/root/data/operations/substract.tres
  addons/gaea/graph/nodes/root/data/operations/substract_datas.tres
  addons/gaea/graph/nodes/root/input/world_size.tres
  addons/gaea/graph/nodes/root/map/filters/random_filter.tres
  addons/gaea/graph/nodes/root/map/functions/map_difference.tres
  addons/gaea/graph/nodes/root/map/functions/map_intersection.tres
  addons/gaea/graph/nodes/root/map/functions/map_union.tres
  addons/gaea/graph/nodes/root/map/mappers/basic_mapper.tres
  addons/gaea/graph/nodes/root/map/mappers/flags_mapper.tres
  addons/gaea/graph/nodes/root/map/mappers/gradient_mapper.tres
  addons/gaea/graph/nodes/root/map/mappers/threshold_mapper.tres
  addons/gaea/graph/nodes/root/map/mappers/value_mapper.tres
  addons/gaea/graph/nodes/root/map/placing/rules_placer.tres
  addons/gaea/graph/nodes/root/map/random/random_scatter.tres
  addons/gaea/graph/nodes/root/other/composition/compose_range.tres
  addons/gaea/graph/nodes/root/scalar/operations/add.tres
  addons/gaea/graph/nodes/root/scalar/operations/divide.tres
  addons/gaea/graph/nodes/root/scalar/operations/multiply.tres
  addons/gaea/graph/nodes/root/scalar/operations/substract.tres
  addons/gaea/graph/nodes/root/vector/composition/compose_vector2.tres
  addons/gaea/graph/nodes/root/vector/composition/compose_vector3.tres
  addons/gaea/graph/nodes/root/vector/decomposition/decompose_vector2.tres
  addons/gaea/graph/nodes/root/vector/decomposition/decompose_vector3.tres
  addons/gaea/graph/nodes/root/vector/operations/add_vector2.tres
  addons/gaea/graph/nodes/root/vector/operations/add_vector3.tres
  addons/gaea/graph/nodes/root/vector/operations/divide_vector2.tres
  addons/gaea/graph/nodes/root/vector/operations/divide_vector3.tres
  addons/gaea/graph/nodes/root/vector/operations/multiply_vector2.tres
  addons/gaea/graph/nodes/root/vector/operations/multiply_vector3.tres
  addons/gaea/graph/nodes/root/vector/operations/substract_vector2.tres
  addons/gaea/graph/nodes/root/vector/operations/substract_vector3.tres
Labels: ignore-for-release, 🧹 organization/clean-up

#290 Add online docs button
  addons/gaea/editor/panel.gd
  addons/gaea/editor/panel.tscn
Labels: 🔨 quality-of-life

#293 Hide arguments when input is connected
  addons/gaea/graph/components/inputs/graph_node_parameter.gd
  addons/gaea/graph/nodes/node.gd
Labels: 🔨 quality-of-life

#295 Fix reroute node
  addons/gaea/graph/nodes/reroute_node.gd
Labels: 🐛 bug

#292 Add more value casting
  addons/gaea/editor/graph_edit.gd
  addons/gaea/graph/nodes/node_resource.gd
Labels: ✨ enhancement

#294 Prioritize updates in the same branch, warn when updating from 1.X to 2.0
  addons/gaea/editor/download_update_panel.gd
  addons/gaea/editor/download_update_panel.tscn
  addons/gaea/editor/update_button.gd
  addons/gaea/editor/update_button.tscn
Labels: 🐛 bug

#297 Fix operating on 2 datas
  addons/gaea/graph/nodes/root/data/operations/datas_operation.gd
Labels: 🐛 bug

#296 Fix casting not working when a non-input argument is present
  addons/gaea/graph/nodes/node_argument.gd
  addons/gaea/graph/nodes/node_resource.gd
Labels: 🐛 bug

#298 Set `resizable` to false on nodes
  addons/gaea/graph/nodes/node.tscn
  addons/gaea/graph/nodes/reroute_node.tscn
Labels: ignore-for-release, 🧹 organization/clean-up

#301 Add Gaea editor settings
  addons/gaea/editor/create_node_tree.gd
  addons/gaea/editor/editor_settings.gd
  addons/gaea/editor/editor_settings.gd.uid
  addons/gaea/editor/graph_edit.gd
  addons/gaea/editor/panel.gd
  addons/gaea/editor/panel.tscn
  addons/gaea/editor/project_settings.gd
  addons/gaea/editor/project_settings.gd.uid
  addons/gaea/gaea.gd
  addons/gaea/graph/components/inputs/graph_node_parameter.gd
  addons/gaea/graph/components/inputs/variable_name_parameter.gd
  addons/gaea/graph/components/slot.gd
  addons/gaea/graph/nodes/node.gd
  addons/gaea/graph/nodes/node_resource.gd
  addons/gaea/graph/nodes/output_node.gd
  addons/gaea/graph/nodes/output_node_resource.gd
  addons/gaea/graph/nodes/preview_texture.gd
  addons/gaea/graph/nodes/reroute_node.gd
  addons/gaea/graph/nodes/root/data/generation/snake_path_2d.gd
  addons/gaea/graph/nodes/variable_node_resource.gd
Labels: 🔨 quality-of-life

#304 Fix wrong argument hiding when it doesn't have an input
  addons/gaea/graph/nodes/node.gd
Labels: 🐛 bug

#307 Add fuzzy search to add node popup
  addons/gaea/editor/create_node_popup.gd
  addons/gaea/editor/create_node_tree.gd
  addons/gaea/editor/panel.gd
  addons/gaea/editor/panel.tscn
Labels: 🔨 quality-of-life

#308 Add "Open In Inspector" context action
  addons/gaea/editor/node_popup.gd
  addons/gaea/editor/panel.tscn
Labels: 🔨 quality-of-life

#309 Add shortcut to cycle between nodes in the 'Create Node' tree
  addons/gaea/editor/create_node_tree.gd
  addons/gaea/editor/panel.tscn
Labels: 🔨 quality-of-life

#318 Pressing 'Enter' when search bar is focused now creates selected node
  addons/gaea/editor/create_node_tree.gd
  addons/gaea/editor/panel.tscn
Labels: 🔨 quality-of-life

#320 Cleanup parameter scenes
  addons/gaea/graph/components/inputs/bitmask_parameter.tscn
  addons/gaea/graph/components/inputs/three_state_button.tscn
  addons/gaea/graph/components/inputs/variable_name_parameter.tscn
Labels: 🧹 organization/clean-up

#321 Fix output node label
  addons/gaea/graph/nodes/output_node.gd
Labels: 🐛 bug, ignore-for-release

#324 Await `_remove_children` to avoid nodes 'leaking' into other graphs when switching generators
  addons/gaea/editor/panel.gd
  addons/gaea/gaea.gd
Labels: 🐛 bug

#323 Save scroll offset during sessions, not in GaeaData
  addons/gaea/editor/panel.gd
  addons/gaea/editor/panel.tscn
  scenes/walker_demo/floor_walker.tres
Labels: 🧹 organization/clean-up

#350 Clean up warnings
  addons/gaea/editor/create_node_popup.gd
  addons/gaea/editor/create_node_tree.gd
  addons/gaea/editor/gradient_visualizer.gd
  addons/gaea/editor/graph_edit.gd
  addons/gaea/editor/panel.gd
  addons/gaea/gaea.gd
  addons/gaea/graph/components/argument_editors/argument_editor.gd
  addons/gaea/graph/components/argument_editors/number_argument_editor.gd
  addons/gaea/graph/graph_nodes/generic_classes/constant.gd
  addons/gaea/graph/graph_nodes/generic_classes/number_operation.gd
  addons/gaea/graph/graph_nodes/generic_classes/parameter.gd
  addons/gaea/graph/graph_nodes/generic_classes/set_operation.gd
  addons/gaea/graph/graph_nodes/node_resource.gd
  addons/gaea/graph/graph_nodes/root/data/basic/fill.gd
  addons/gaea/graph/graph_nodes/root/data/border/border.gd
  addons/gaea/graph/graph_nodes/root/data/filters/distance_filter.gd
  addons/gaea/graph/graph_nodes/root/data/filters/filter.gd
  addons/gaea/graph/graph_nodes/root/data/filters/flags_filter.gd
  addons/gaea/graph/graph_nodes/root/data/filters/random_filter.gd
  addons/gaea/graph/graph_nodes/root/data/filters/threshold_filter.gd
  addons/gaea/graph/graph_nodes/root/data/generation/falloff_map.gd
  addons/gaea/graph/graph_nodes/root/data/generation/floor_walker.gd
  addons/gaea/graph/graph_nodes/root/data/generation/snake_path_2d.gd
  addons/gaea/graph/graph_nodes/root/data/noise/noise.gd
  addons/gaea/graph/graph_nodes/root/data/operations/datas/datas_operation.gd
  addons/gaea/graph/graph_nodes/root/data/operations/scalar/data_operation.gd
  addons/gaea/graph/graph_nodes/root/data/operations/sets/data_set_operation.gd
  addons/gaea/graph/graph_nodes/root/map/filters/random_filter.gd
  addons/gaea/graph/graph_nodes/root/map/mappers/basic_mapper.gd
  addons/gaea/graph/graph_nodes/root/map/mappers/gradient_mapper.gd
  addons/gaea/graph/graph_nodes/root/map/operations/map_set_operation.gd
  addons/gaea/graph/graph_nodes/root/map/placing/random_scatter.gd
  addons/gaea/graph/graph_nodes/root/map/placing/rules_placer.gd
  addons/gaea/graph/graph_nodes/root/other/composition/compose_range.gd
  addons/gaea/graph/graph_nodes/root/other/constants/range_constant.gd
  addons/gaea/graph/graph_nodes/root/scalar/constants/float_constant.gd
  addons/gaea/graph/graph_nodes/root/scalar/constants/int_constant.gd
  addons/gaea/graph/graph_nodes/root/scalar/operations/float_operation.gd
  addons/gaea/graph/graph_nodes/root/scalar/operations/int_operation.gd
  addons/gaea/graph/graph_nodes/root/vector/composition/compose_vector.gd
  addons/gaea/graph/graph_nodes/root/vector/composition/decompose_vector.gd
  addons/gaea/graph/graph_nodes/root/vector/constants/vector2_constant.gd
  addons/gaea/graph/graph_nodes/root/vector/constants/vector2i_constant.gd
  addons/gaea/graph/graph_nodes/root/vector/constants/vector3_constant.gd
  addons/gaea/graph/graph_nodes/root/vector/constants/vector3i_constant.gd
  addons/gaea/graph/graph_nodes/special/reroute/reroute_node_resource.gd
  addons/gaea/nodes/chunk_loaders/chunk_loader_2d.gd
  addons/gaea/nodes/generator.gd
  addons/gaea/nodes/renderers/renderer.gd
  addons/gaea/resources/gaea_value.gd
  addons/gaea/resources/material_gradient/material_gradient.gd
Labels: 🧹 organization/clean-up
