Repository gaea-godot/gaea, pull requests merged in 2025-03, with the labels that each got.

#191 Allow changing Frame's tint color
  addons/gaea/editor/node_popup.gd
  addons/gaea/editor/panel.gd
Labels: ✨ enhancement

#190 Implement 'salt' for nodes
  addons/gaea/graph/nodes/node.gd
  addons/gaea/graph/nodes/node_resource.gd
  addons/gaea/graph/nodes/output_node_resource.tres
  addons/gaea/graph/nodes/root/data/generation/snake_path_2d.gd
  addons/gaea/graph/nodes/root/data/noise/simplex_smooth.gd
  scenes/test/test_scene.tscn
Labels: ✨ enhancement

#192 Add FloorWalkerXY and FloorWalkerXZ
  addons/gaea/editor/panel.tscn
  addons/gaea/graph/components/inputs/number_parameter.gd
  addons/gaea/graph/components/inputs/range_parameter.gd
  addons/gaea/graph/components/inputs/vector2_parameter.tscn
  addons/gaea/graph/components/inputs/vector3_parameter.gd
  addons/gaea/graph/components/inputs/vector3_parameter.gd.uid
  addons/gaea/graph/components/inputs/vector3_parameter.tscn
  addons/gaea/graph/nodes/node.gd
  addons/gaea/graph/nodes/node.tscn
  addons/gaea/graph/nodes/node_argument.gd
  addons/gaea/graph/nodes/output_node_resource.tres
  addons/gaea/graph/nodes/root/data/basic/fill.tres
  addons/gaea/graph/nodes/root/data/functions/merge_data.tres
  addons/gaea/graph/nodes/root/data/generation/floor_walker.gd
  addons/gaea/graph/nodes/root/data/generation/floor_walker.gd.uid
  addons/gaea/graph/nodes/root/data/generation/floor_walker_xy.tres
  addons/gaea/graph/nodes/root/data/generation/floor_walker_xz.tres
  addons/gaea/graph/nodes/root/data/generation/snake_path_2d.tres
  addons/gaea/graph/nodes/root/data/noise/simplex_smooth_2D.tres
  addons/gaea/graph/nodes/root/data/noise/simplex_smooth_3D.tres
  addons/gaea/graph/nodes/root/data/operations/add.tres
  addons/gaea/graph/nodes/root/data/operations/divide.tres
  addons/gaea/graph/nodes/root/data/operations/multiply.tres
  addons/gaea/graph/nodes/root/input/composition/compose_range.tres
  addons/gaea/graph/nodes/root/input/variables/bool_variable.tres
  addons/gaea/graph/nodes/root/input/variables/float_variable.tres
  addons/gaea/graph/nodes/root/input/variables/int_variable.tres
  addons/gaea/graph/nodes/root/input/variables/material_variable.tres
  addons/gaea/graph/nodes/root/map/functions/merge_maps.tres
  addons/gaea/graph/nodes/root/map/mappers/flags_mapper.tres
  addons/gaea/graph/nodes/root/map/mappers/threshold_mapper.tres
Labels: ✨ enhancement

#194 Remove test scene folder from .gitignore
  .gitignore
  scenes/test/rooms_tileset_test.png
  scenes/test/rooms_tileset_test.png.import
  scenes/test/snake_path_generation.tres
  scenes/test/test_actor.gd
  scenes/test/test_actor.gd.uid
  scenes/test/test_scene.gd
  scenes/test/test_scene.gd.uid
  scenes/test/test_scene.tscn
  scenes/test/test_scene.tscn-2TgRbk
  scenes/test/test_tileset.png
  scenes/test/test_tileset.png.import
Labels: ✨ enhancement

#193 Remove wrong information from SnakePath2D description
  addons/gaea/graph/nodes/root/data/generation/snake_path_2d.gd
  addons/gaea/graph/nodes/root/data/generation/snake_path_2d.tres
Labels: 🐛 bug

#195 Add Vector2/3-related nodes
  addons/gaea/assets/types/vec2i.svg
  addons/gaea/assets/types/vec2i.svg.import
  addons/gaea/assets/types/vec3.svg
  addons/gaea/assets/types/vec3.svg.import
  addons/gaea/assets/types/vec3i.svg
  addons/gaea/assets/types/vec3i.svg.import
  addons/gaea/graph/components/inputs/vector2_parameter.tscn
  addons/gaea/graph/components/inputs/vector3_parameter.tscn
  addons/gaea/graph/nodes/node_resource.gd
  addons/gaea/graph/nodes/root/input/composition/compose_vector.gd
  addons/gaea/graph/nodes/root/input/composition/compose_vector.gd.uid
  addons/gaea/graph/nodes/root/input/composition/compose_vector2.tres
  addons/gaea/graph/nodes/root/input/composition/compose_vector3.tres
  addons/gaea/graph/nodes/root/input/decomposition/decompose_vector.gd
  addons/gaea/graph/nodes/root/input/decomposition/decompose_vector.gd.uid
  addons/gaea/graph/nodes/root/input/decomposition/decompose_vector2.tres
  addons/gaea/graph/nodes/root/input/decomposition/decompose_vector3.tres
  addons/gaea/graph/nodes/root/input/variables/variable_node.gd
  addons/gaea/graph/nodes/root/input/variables/vector2_variable.tres
  addons/gaea/graph/nodes/root/input/variables/vector2i_variable.tres
  addons/gaea/graph/nodes/root/input/variables/vector3_variable.tres
  addons/gaea/graph/nodes/root/input/variables/vector3i_variable.tres
Labels: ✨ enhancement

#196 Add map previews
  addons/gaea/graph/nodes/preview_texture.gd
  addons/gaea/graph/nodes/root/map/functions/merge_maps.tres
  addons/gaea/graph/nodes/root/map/mappers/flags_mapper.tres
  addons/gaea/graph/nodes/root/map/mappers/threshold_mapper.gd
  addons/gaea/resources/materials/gaea_material.gd
Labels: ✨ enhancement

#197 Add constants and WorldSize nodes
  addons/gaea/graph/components/inputs/graph_node_parameter.gd
  addons/gaea/graph/components/inputs/vector3_parameter.gd
  addons/gaea/graph/nodes/node.gd
  addons/gaea/graph/nodes/node_argument.gd
  addons/gaea/graph/nodes/node_resource.gd
  addons/gaea/graph/nodes/root/data/basic/fill.gd
  addons/gaea/graph/nodes/root/data/basic/fill.tres
  addons/gaea/graph/nodes/root/data/generation/floor_walker.gd
  addons/gaea/graph/nodes/root/data/generation/floor_walker_xy.tres
  addons/gaea/graph/nodes/root/data/generation/floor_walker_xz.tres
  addons/gaea/graph/nodes/root/data/generation/snake_path_2d.tres
  addons/gaea/graph/nodes/root/data/noise/simplex_smooth_2D.tres
  addons/gaea/graph/nodes/root/data/noise/simplex_smooth_3D.tres
  addons/gaea/graph/nodes/root/data/operations/add.tres
  addons/gaea/graph/nodes/root/data/operations/divide.tres
  addons/gaea/graph/nodes/root/data/operations/multiply.tres
  addons/gaea/graph/nodes/root/input/composition/compose_range.tres
  addons/gaea/graph/nodes/root/input/composition/compose_vector2.tres
  addons/gaea/graph/nodes/root/input/composition/compose_vector3.tres
  addons/gaea/graph/nodes/root/input/constants/bool_constant.tres
  addons/gaea/graph/nodes/root/input/constants/constant.gd
  addons/gaea/graph/nodes/root/input/constants/constant.gd.uid
  addons/gaea/graph/nodes/root/input/constants/float_constant.tres
  addons/gaea/graph/nodes/root/input/constants/int_constant.tres
  addons/gaea/graph/nodes/root/input/constants/vector2_constant.tres
  addons/gaea/graph/nodes/root/input/constants/vector3_constant.tres
  addons/gaea/graph/nodes/root/input/decomposition/decompose_vector2.tres
  addons/gaea/graph/nodes/root/input/decomposition/decompose_vector3.tres
  addons/gaea/graph/nodes/root/input/utilities/world_size.gd
  addons/gaea/graph/nodes/root/input/utilities/world_size.gd.uid
  addons/gaea/graph/nodes/root/input/utilities/world_size.tres
  addons/gaea/graph/nodes/root/input/variables/bool_variable.tres
  addons/gaea/graph/nodes/root/input/variables/float_variable.tres
  addons/gaea/graph/nodes/root/input/variables/int_variable.tres
  addons/gaea/graph/nodes/root/input/variables/material_variable.tres
  addons/gaea/graph/nodes/root/input/variables/vector2_variable.tres
  addons/gaea/graph/nodes/root/input/variables/vector2i_variable.tres
  addons/gaea/graph/nodes/root/input/variables/vector3_variable.tres
  addons/gaea/graph/nodes/root/input/variables/vector3i_variable.tres
  addons/gaea/graph/nodes/root/map/mappers/flags_mapper.tres
  addons/gaea/graph/nodes/root/map/mappers/threshold_mapper.tres
Labels: ✨ enhancement

#201 Reduce minimum node X size
  addons/gaea/graph/nodes/node.tscn
Labels: ✨ enhancement

#205 Update TileMapGaeaRenderer and TileMapMaterial
  addons/gaea/nodes/renderers/tilemap_renderer.gd
  addons/gaea/resources/materials/tilemap_material.gd
Labels: ✨ enhancement

#206 Add RandomScatter node
  addons/gaea/graph/nodes/root/map/random/random_scatter.gd
  addons/gaea/graph/nodes/root/map/random/random_scatter.gd.uid
  addons/gaea/graph/nodes/root/map/random/random_scatter.tres
Labels: ✨ enhancement

#207 Rename Merge to Union and add Intersection, Difference and Complement nodes
  addons/gaea/graph/nodes/complement.gd
  addons/gaea/graph/nodes/complement.gd.uid
  addons/gaea/graph/nodes/difference.gd
  addons/gaea/graph/nodes/difference.gd.uid
  addons/gaea/graph/nodes/intersection.gd
  addons/gaea/graph/nodes/intersection.gd.uid
  addons/gaea/graph/nodes/root/data/functions/data_complement.tres
  addons/gaea/graph/nodes/root/data/functions/data_difference.tres
  addons/gaea/graph/nodes/root/data/functions/data_intersection.tres
  addons/gaea/graph/nodes/root/data/functions/data_union.tres
  addons/gaea/graph/nodes/root/map/functions/map_difference.tres
  addons/gaea/graph/nodes/root/map/functions/map_intersection.tres
  addons/gaea/graph/nodes/root/map/functions/map_union.tres
  addons/gaea/graph/nodes/root/map/mappers/basic_mapper.gd
  addons/gaea/graph/nodes/root/map/mappers/flags_mapper.gd
  addons/gaea/graph/nodes/root/map/mappers/threshold_mapper.gd
  addons/gaea/graph/nodes/root/map/mappers/value_mapper.gd
  addons/gaea/graph/nodes/union.gd
  addons/gaea/graph/nodes/union.gd.uid
Labels: ✨ enhancement

#208 Fix some problems when passing-in data
  addons/gaea/graph/nodes/root/data/filters/distance_filter.gd
  addons/gaea/graph/nodes/root/data/filters/filter.gd
  addons/gaea/graph/nodes/root/data/filters/flags_filter.gd
  addons/gaea/graph/nodes/root/data/filters/threshold_filter.gd
  addons/gaea/graph/nodes/root/data/operations/add.tres
  addons/gaea/graph/nodes/root/data/operations/divide.tres
  addons/gaea/graph/nodes/root/data/operations/operation.gd
  addons/gaea/graph/nodes/root/map/random/random_scatter.gd
Labels: 🐛 bug

#210 Fix for Node Popup position breaking when the editor window is on a second monitor.
  addons/gaea/editor/node_popup.gd
  addons/gaea/editor/panel.gd
Labels: 🐛 bug

#209 Add Border2D node
  addons/gaea/graph/components/inputs/bitmask_parameter.gd
  addons/gaea/graph/components/inputs/neighbor_parameter.gd
  addons/gaea/graph/components/inputs/neighbor_parameter.gd.uid
  addons/gaea/graph/components/inputs/neighbor_parameter.tscn
  addons/gaea/graph/nodes/difference.gd
  addons/gaea/graph/nodes/node_argument.gd
  addons/gaea/graph/nodes/root/data/border/border.gd
  addons/gaea/graph/nodes/root/data/border/border.gd.uid
  addons/gaea/graph/nodes/root/data/border/border.tres
  addons/gaea/graph/nodes/root/data/generation/floor_walker.gd
  addons/gaea/graph/nodes/root/map/random/random_scatter.gd
Labels: ✨ enhancement

#211 Optimize preview
  addons/gaea/graph/nodes/preview_texture.gd
Labels: 👨‍💻 optimization

#212 Fix idx bug, allow sub-frames and fix frames not saving attached nodes correctly
  addons/gaea/editor/graph_edit.gd
  addons/gaea/editor/panel.gd
  addons/gaea/graph/nodes/complement.gd
  addons/gaea/graph/nodes/output_node_resource.gd
  addons/gaea/graph/nodes/root/data/border/border.gd
  addons/gaea/graph/nodes/root/data/filters/filter.gd
  addons/gaea/graph/nodes/root/data/operations/operation.gd
  addons/gaea/graph/nodes/root/map/mappers/basic_mapper.gd
Labels: 🐛 bug

#213 Upload Walker demo
  project.godot
  scenes/walker_demo/floor_walker.tres
  scenes/walker_demo/scene.tscn
  scenes/walker_demo/tileset.png
  scenes/walker_demo/tileset.png.import
Labels: 📖 documentation

#214 Remove all warnings
  addons/gaea/graph/components/inputs/graph_node_parameter.gd
  addons/gaea/graph/components/inputs/variable_name_parameter.gd
  addons/gaea/graph/nodes/complement.gd
  addons/gaea/graph/nodes/difference.gd
  addons/gaea/graph/nodes/node.gd
  addons/gaea/graph/nodes/node_argument.gd
  addons/gaea/graph/nodes/output_node.gd
  addons/gaea/graph/nodes/root/data/border/border.gd
  addons/gaea/graph/nodes/root/data/filters/distance_filter.gd
  addons/gaea/graph/nodes/root/data/filters/filter.gd
  addons/gaea/graph/nodes/root/data/generation/floor_walker.gd
  addons/gaea/graph/nodes/root/input/variables/variable_node.gd
  addons/gaea/graph/nodes/root/map/mappers/basic_mapper.gd
  addons/gaea/graph/nodes/root/map/random/random_scatter.gd
  addons/gaea/graph/nodes/union.gd
  addons/gaea/graph/nodes/variable_node.gd
  addons/gaea/nodes/generator.gd
  addons/gaea/nodes/renderers/renderer.gd
Labels: 🐛 bug

#215 Add RulesPlacer node, inspired by LDtk
  addons/gaea/assets/check.svg
  addons/gaea/assets/check.svg.import
  addons/gaea/assets/cross.svg
  addons/gaea/assets/cross.svg.import
  addons/gaea/graph/components/inputs/rules_parameter.gd
  addons/gaea/graph/components/inputs/rules_parameter.gd.uid
  addons/gaea/graph/components/inputs/rules_parameter.tscn
  addons/gaea/graph/components/inputs/three_state_button.gd
  addons/gaea/graph/components/inputs/three_state_button.gd.uid
  addons/gaea/graph/components/inputs/three_state_button.tscn
  addons/gaea/graph/nodes/node_argument.gd
  addons/gaea/graph/nodes/node_resource.gd
  addons/gaea/graph/nodes/root/map/placing/rules_placer.gd
  addons/gaea/graph/nodes/root/map/placing/rules_placer.gd.uid
  addons/gaea/graph/nodes/root/map/placing/rules_placer.tres
Labels: ✨ enhancement
