Repository gaea-godot/gaea, pull requests merged in 2025-05, with the labels that each got.

#368 Remove old saved properties from `BoolArgumentEditor`
  addons/gaea/graph/components/argument_editors/boolean_argument_editor.tscn
Labels: 🧹 organization/clean-up

#372 Update enum cases to uppercase
  addons/gaea/graph/graph_nodes/generic_classes/number_operation.gd
  addons/gaea/graph/graph_nodes/node_resource.gd
  addons/gaea/graph/graph_nodes/root/data/operations/datas/datas_operation.gd
  addons/gaea/graph/graph_nodes/root/vector/operations/vector_operation.gd
  addons/gaea/resources/gaea_data.gd
Labels: 🧹 organization/clean-up

#354 Add GridMapGaeaRenderer missing methods
  addons/gaea/nodes/renderers/gridmap_renderer.gd
Labels: 🐛 bug

#375 Update missing enum cases to uppercase
  addons/gaea/graph/graph_nodes/root/data/operations/scalar/data_operation.gd
  addons/gaea/graph/graph_nodes/root/scalar/operations/float_operation.gd
  addons/gaea/graph/graph_nodes/root/scalar/operations/int_operation.gd
  addons/gaea/resources/gaea_data_migration.gd
Labels: 🧹 organization/clean-up

#367 Add new shapes to `GaeaNodeFalloff`
  addons/gaea/graph/graph_nodes/root/data/generation/falloff_map.gd
Labels: ✨ enhancement

#359 Rework `GaeaMaterial`s to allow them to be sampled and make `GaeaMaterialGradient` into a material
  addons/gaea/assets/types/material_gradient.svg
  addons/gaea/assets/types/material_gradient.svg.import
  addons/gaea/editor/editor_settings.gd
  addons/gaea/editor/gradient_visualizer.gd
  addons/gaea/editor/inspector_plugin.gd
  addons/gaea/graph/graph_nodes/node_resource.gd
  addons/gaea/graph/graph_nodes/root/map/mappers/basic_mapper.gd
  addons/gaea/graph/graph_nodes/root/map/mappers/gradient_mapper.gd
  addons/gaea/graph/graph_nodes/root/map/mappers/gradient_mapper.gd.uid
  addons/gaea/graph/graph_nodes/root/map/placing/random_scatter.gd
  addons/gaea/graph/graph_nodes/root/map/placing/rules_placer.gd
  addons/gaea/graph/graph_nodes/root/resources/variables/gradient_parameter.gd
  addons/gaea/graph/graph_nodes/root/resources/variables/gradient_parameter.gd.uid
  addons/gaea/nodes/renderers/gridmap_renderer.gd
  addons/gaea/nodes/renderers/tilemap_renderer.gd
  addons/gaea/resources/gaea_data.gd
  addons/gaea/resources/gaea_data_migration.gd
  addons/gaea/resources/gaea_value.gd
  addons/gaea/resources/materials/data/gridmap_material.gd
  addons/gaea/resources/materials/data/gridmap_material.gd.uid
  addons/gaea/resources/materials/data/tilemap_material.gd
  addons/gaea/resources/materials/data/tilemap_material.gd.uid
  addons/gaea/resources/materials/distribution/gradient_material.gd
  addons/gaea/resources/materials/distribution/gradient_material.gd.uid
  addons/gaea/resources/materials/distribution/pick_random_material.gd
  addons/gaea/resources/materials/distribution/pick_random_material.gd.uid
  addons/gaea/resources/materials/distribution/pointwise_random_material.gd
  addons/gaea/resources/materials/distribution/pointwise_random_material.gd.uid
  addons/gaea/resources/materials/gaea_material.gd
Labels: ✨ enhancement, 🧹 organization/clean-up

#373 Add a Texture data type and a TextureSampler node
  addons/gaea/editor/editor_settings.gd
  addons/gaea/graph/graph_nodes/root/resources/samplers/texture_sampler.gd
  addons/gaea/graph/graph_nodes/root/resources/samplers/texture_sampler.gd.uid
  addons/gaea/graph/graph_nodes/root/resources/variables/texture_2d_parameter.gd
  addons/gaea/graph/graph_nodes/root/resources/variables/texture_2d_parameter.gd.uid
  addons/gaea/graph/graph_nodes/root/resources/variables/texture_3d_parameter.gd
  addons/gaea/graph/graph_nodes/root/resources/variables/texture_3d_parameter.gd.uid
  addons/gaea/resources/gaea_value.gd
Labels: ✨ enhancement

#379 Rebuild graph nodes when their resource script is changed
  addons/gaea/editor/graph_edit.gd
Labels: 🔨 quality-of-life

#382 Hide tooltip when no description is provided
  addons/gaea/graph/graph_nodes/node.gd
Labels: 🧹 organization/clean-up

#360 Removed uid prefix in migration
  addons/gaea/resources/gaea_data_migration.gd
Labels: 🐛 bug

#370 Make categories collapsable
  addons/gaea/graph/components/argument_editors/argument_editor.gd
  addons/gaea/graph/components/argument_editors/argument_editor.tscn
  addons/gaea/graph/components/argument_editors/category.gd
  addons/gaea/graph/components/argument_editors/category.gd.uid
  addons/gaea/graph/components/argument_editors/category.tscn
  addons/gaea/graph/components/argument_editors/range_argument_editor.tscn
  addons/gaea/graph/graph_nodes/node.gd
  addons/gaea/resources/gaea_value.gd
Labels: 🔨 quality-of-life

#380 Validate Script Type Before Adding to Node Tree
  addons/gaea/editor/create_node_tree.gd
Labels: 🧹 organization/clean-up

#378 Add documentation button to GaeaGraphNode
  addons/gaea/graph/graph_nodes/node.gd
Labels: 🔨 quality-of-life

#374 Add slider when number argument is min/maxed
  addons/gaea/graph/components/argument_editors/category.gd.uid
  addons/gaea/graph/components/argument_editors/number_argument_editor.gd
  addons/gaea/graph/components/argument_editors/number_argument_editor.tscn
Labels: 🔨 quality-of-life

#384 Enable select all on focus for text editor fields
  addons/gaea/graph/components/argument_editors/number_argument_editor.tscn
  addons/gaea/graph/components/argument_editors/parameter_name_argument_editor.tscn
  addons/gaea/graph/components/argument_editors/range_argument_editor.tscn
  addons/gaea/graph/components/argument_editors/vector_argument_editor.tscn
Labels: 🔨 quality-of-life

#385 Improve display of Vector argument editor and fix 2D type switching to 3D when connecting
  addons/gaea/graph/components/argument_editors/vector_argument_editor.gd
  addons/gaea/graph/components/argument_editors/vector_argument_editor.tscn
Labels: 🐛 bug, ⌨️ interface

#383 Save opened preview state on rebuild
  addons/gaea/graph/components/preview_texture.gd
  addons/gaea/graph/graph_nodes/node.gd
Labels: 🔨 quality-of-life, ⌨️ interface

#377 Rename GaeaData to GaeaGraph
  addons/gaea/editor/node_popup.gd
  addons/gaea/editor/panel.gd
  addons/gaea/graph/graph_nodes/generic_classes/constant.gd
  addons/gaea/graph/graph_nodes/generic_classes/number_operation.gd
  addons/gaea/graph/graph_nodes/generic_classes/parameter.gd
  addons/gaea/graph/graph_nodes/generic_classes/set_operation.gd
  addons/gaea/graph/graph_nodes/node.gd
  addons/gaea/graph/graph_nodes/node_resource.gd
  addons/gaea/graph/graph_nodes/root/data/basic/fill.gd
  addons/gaea/graph/graph_nodes/root/data/border/border.gd
  addons/gaea/graph/graph_nodes/root/data/filters/distance_filter.gd
  addons/gaea/graph/graph_nodes/root/data/filters/filter.gd
  addons/gaea/graph/graph_nodes/root/data/filters/flags_filter.gd
  addons/gaea/graph/graph_nodes/root/data/filters/random_filter.gd
  addons/gaea/graph/graph_nodes/root/data/filters/threshold_filter.gd
  addons/gaea/graph/graph_nodes/root/data/generation/falloff_map.gd
  addons/gaea/graph/graph_nodes/root/data/generation/floor_walker.gd
  addons/gaea/graph/graph_nodes/root/data/generation/snake_path_2d.gd
  addons/gaea/graph/graph_nodes/root/data/noise/noise.gd
  addons/gaea/graph/graph_nodes/root/data/operations/datas/datas_operation.gd
  addons/gaea/graph/graph_nodes/root/data/operations/scalar/data_operation.gd
  addons/gaea/graph/graph_nodes/root/input/input.gd
  addons/gaea/graph/graph_nodes/root/map/mappers/basic_mapper.gd
  addons/gaea/graph/graph_nodes/root/map/mappers/flags_mapper.gd
  addons/gaea/graph/graph_nodes/root/map/mappers/threshold_mapper.gd
  addons/gaea/graph/graph_nodes/root/map/mappers/value_mapper.gd
  addons/gaea/graph/graph_nodes/root/map/placing/random_scatter.gd
  addons/gaea/graph/graph_nodes/root/map/placing/rules_placer.gd
  addons/gaea/graph/graph_nodes/root/other/composition/compose_range.gd
  addons/gaea/graph/graph_nodes/root/resources/samplers/texture_sampler.gd
  addons/gaea/graph/graph_nodes/root/vector/composition/compose_vector.gd
  addons/gaea/graph/graph_nodes/root/vector/composition/decompose_vector.gd
  addons/gaea/graph/graph_nodes/root/vector/operations/vector_operation.gd
  addons/gaea/graph/graph_nodes/special/output/output_node_resource.gd
  addons/gaea/graph/graph_nodes/special/reroute/reroute_node_resource.gd
  addons/gaea/nodes/generator.gd
  addons/gaea/nodes/renderers/gridmap_renderer.gd
  addons/gaea/nodes/renderers/tilemap_renderer.gd
  addons/gaea/resources/gaea_graph.gd
  addons/gaea/resources/gaea_graph.gd.uid
  addons/gaea/resources/gaea_graph_migration.gd
  addons/gaea/resources/gaea_graph_migration.gd.uid
  scenes/walker_demo/floor_walker.tres
  script_templates/GaeaNodeResource/simple.gd
  script_templates/GaeaNodeResource/with_enum.gd
Labels: 🧹 organization/clean-up

#387 Change the way parameter names are edited
  addons/gaea/graph/components/argument_editors/parameter_name_argument_editor.gd
  addons/gaea/graph/components/argument_editors/parameter_name_argument_editor.tscn
  addons/gaea/graph/graph_nodes/generic_classes/parameter_node.gd
Labels: ⌨️ interface

#389 Change GaeaGraph icon to graph icon
  addons/gaea/assets/data.svg
  addons/gaea/assets/graph.svg
  addons/gaea/assets/graph.svg.import
  addons/gaea/resources/gaea_graph.gd
Labels: ⌨️ interface

#392 Fix `NumberArgumentEditor` setting min and max incorrectly
  addons/gaea/graph/components/argument_editors/number_argument_editor.gd
Labels: 🐛 bug

#390 Change usages of `Axis` with `Vector3i.Axis`
  addons/gaea/graph/graph_nodes/generic_classes/set_operation.gd
  addons/gaea/graph/graph_nodes/node_resource.gd
  addons/gaea/graph/graph_nodes/root/data/basic/fill.gd
  addons/gaea/graph/graph_nodes/root/data/border/border.gd
  addons/gaea/graph/graph_nodes/root/data/generation/falloff_map.gd
  addons/gaea/graph/graph_nodes/root/data/noise/noise.gd
  addons/gaea/graph/graph_nodes/root/map/placing/rules_placer.gd
  addons/gaea/graph/graph_nodes/root/resources/samplers/texture_sampler.gd
Labels: 🧹 organization/clean-up

#394 Abstract frames into a `GaeaGraphFrame` class
  addons/gaea/editor/graph_edit.gd
  addons/gaea/editor/node_popup.gd
  addons/gaea/editor/panel.gd
  addons/gaea/graph/graph_nodes/graph_frame.gd
  addons/gaea/graph/graph_nodes/graph_frame.gd.uid
  addons/gaea/graph/graph_nodes/node.gd
  addons/gaea/resources/gaea_graph.gd
  scenes/walker_demo/floor_walker.tres
Labels: 🐛 bug, 🧹 organization/clean-up

#398 Fix prepare_sample error message in mappers
  addons/gaea/graph/graph_nodes/root/map/mappers/basic_mapper.gd
  addons/gaea/graph/graph_nodes/root/map/placing/random_scatter.gd
  addons/gaea/graph/graph_nodes/root/map/placing/rules_placer.gd
Labels: 🐛 bug

#401 Fix `TilemapGaeaRenderer` rendering wrong terrain
  addons/gaea/nodes/renderers/tilemap_renderer.gd
Labels: 🐛 bug

#400 Add `GaeaNodeResource` tests
  .github/workflows/generation_testing.yml
  .github/workflows/nodes_testing.yml
  .gitignore
  addons/gdUnit4/GdUnitRunner.cfg
  project.godot
  testing/generation/generate_test.gd
  testing/graph_nodes/general/root_nodes_testing.gd
  testing/graph_nodes/general/root_nodes_testing.gd.uid
Labels: repository

#399 Move `_log_data` call to `traverse()`
  addons/gaea/graph/graph_nodes/generic_classes/constant.gd
  addons/gaea/graph/graph_nodes/generic_classes/number_operation.gd
  addons/gaea/graph/graph_nodes/generic_classes/parameter.gd
  addons/gaea/graph/graph_nodes/generic_classes/set_operation.gd
  addons/gaea/graph/graph_nodes/node_resource.gd
  addons/gaea/graph/graph_nodes/root/data/basic/fill.gd
  addons/gaea/graph/graph_nodes/root/data/border/border.gd
  addons/gaea/graph/graph_nodes/root/data/filters/filter.gd
  addons/gaea/graph/graph_nodes/root/data/generation/falloff_map.gd
  addons/gaea/graph/graph_nodes/root/data/generation/floor_walker.gd
  addons/gaea/graph/graph_nodes/root/data/generation/snake_path_2d.gd
  addons/gaea/graph/graph_nodes/root/data/noise/noise.gd
  addons/gaea/graph/graph_nodes/root/data/operations/datas/datas_operation.gd
  addons/gaea/graph/graph_nodes/root/data/operations/scalar/data_operation.gd
  addons/gaea/graph/graph_nodes/root/input/input.gd
  addons/gaea/graph/graph_nodes/root/map/mappers/basic_mapper.gd
  addons/gaea/graph/graph_nodes/root/map/placing/random_scatter.gd
  addons/gaea/graph/graph_nodes/root/map/placing/rules_placer.gd
  addons/gaea/graph/graph_nodes/root/other/composition/compose_range.gd
  addons/gaea/graph/graph_nodes/root/resources/samplers/texture_sampler.gd
  addons/gaea/graph/graph_nodes/root/vector/composition/compose_vector.gd
  addons/gaea/graph/graph_nodes/root/vector/composition/decompose_vector.gd
  addons/gaea/graph/graph_nodes/root/vector/operations/vector_operation.gd
  script_templates/GaeaNodeResource/simple.gd
  script_templates/GaeaNodeResource/with_enum.gd
Labels: 🧹 organization/clean-up

#405 Fix clearing functionality of `GridMapGaeaRenderer`
  addons/gaea/nodes/renderers/gridmap_renderer.gd
Labels: 🐛 bug

#406 Don't clamp gradient material sampling to 0.0-1.0
  addons/gaea/resources/materials/distribution/gradient_material.gd
Labels: ✨ enhancement

#403 Add the `ToHeight2D/3D` node, used to create side-view or 3D terrain.
  addons/gaea/graph/graph_nodes/root/data/generation/snake_path_2d.gd
  addons/gaea/graph/graph_nodes/root/data/transformation/to_height.gd
  addons/gaea/graph/graph_nodes/root/data/transformation/to_height.gd.uid
  testing/graph_nodes/to_height/to_height_2d_and_3d.gd
  testing/graph_nodes/to_height/to_height_2d_and_3d.gd.uid
Labels: ✨ enhancement
